dist: trusty
language: node_js

node_js:
  - 9
  - 10
  - 11
  - 12

git:
  depth: 5
cache:
  directories:
    - node_modules

before_install: npm i -g npm@latest

install:
  - npm install --save-dev nyc
  - npm install --save-dev mocha
  - npm install -save-dev chai
script:
  - npm run coverage
